version: "3.7"
services:
  database:
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    hostname: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    restart: unless-stopped

volumes:
  data:
